#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#
# Generates TB520FUCustomFeatures/res/values*/strings.xml for the "Custom
# Tweaks" app of the optional TB520FU customizations (game performance and
# Play Integrity Fix). English is the default; strings equal to English
# are left out of the translations so they fall back to it.
import os, re

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..',
                   'TB520FUCustomFeatures', 'res')

KEYS = [
 ('app_name', None), ('app_summary', None),
 ('game_perf_title', None), ('game_perf_summary', None),
 ('game_perf_on', None), ('game_perf_off', None),
 ('game_perf_main_switch', None),
 ('game_mem_clean_title', None), ('game_mem_clean_summary', None),
 ('game_apps_category', None), ('game_app_add', None), ('game_app_remove', None),
 ('game_app_levels', None),
 ('game_cpu_category', None), ('game_gpu_category', None),
 ('game_perf_footer', None),
 ('game_custom_cpu_title', None),
 ('game_custom_gpu_title', None), ('game_custom_range_summary', None),
 ('game_custom_cpu_summary', None), ('game_custom_gpu_summary', None),
 ('game_custom_level', None),
 ('play_store_category', 'Play Store'),
 ('installer_spoof_title', None), ('installer_spoof_summary', None),
 ('reboot_title', None), ('reboot_now', None), ('reboot_later', None),
 ('integrity_fix_title', None), ('integrity_fix_summary', None),
 ('integrity_settings_title', None), ('integrity_settings_summary', None),
('cooldown_category', None), ('check_period_title', None), ('unlock_cooldown_title', None),
 ('keybox_manager_title', None),
 ('teesim_title', None),
 ('pif_title', None),
 ('integrity_reboot_message', None), ('integrity_reboot_off_message', None),
 ('integrity_status_category', None),
 ('keybox_state_title', None), ('keybox_state_installed', None),
 ('keybox_state_none', None), ('keybox_state_unavailable', None),
 ('keybox_state_revoked', None),
 ('keybox_source_title', None), ('keybox_serial_title', None),
 ('keybox_auto_title', None), ('keybox_auto_summary', None),
 ('keybox_auto_rotate_title', None), ('keybox_auto_rotate_summary', None),
 ('keybox_renew_title', None), ('keybox_renew_summary', None),
 ('keybox_renewing', None), ('keybox_renew_ok', None), ('keybox_renew_failed', None),
 ('keybox_clear_title', None), ('keybox_clear_summary', None),
 ('keybox_clear_confirm', None), ('keybox_cleared', None),
 ('keybox_pool_title', None), ('keybox_pool_summary', None), ('keybox_pool_none', None),
 ('teesim_state_title', None), ('teesim_on', None), ('teesim_off', None),
 ('teesim_keybox_title', None),
 ('teesim_targets_category', None), ('teesim_targets_all', None),
 ('teesim_targets_all_summary', None),
 ('teesim_target_add', None), ('teesim_target_remove', None),
 ('teesim_target_remove_confirm', None),
 ('teesim_auto_category', None),
 ('teesim_auto_title', None), ('teesim_auto_summary', None),
 ('teesim_add_all', None), ('teesim_add_all_summary', None),
 ('teesim_add_all_done', None),
 ('pif_state_title', None), ('pif_state_none', None),
 ('pif_state_user', None), ('pif_state_fetched', None),
 ('pif_patch_title', None), ('pif_fingerprint_title', None),
 ('pif_refresh_title', None), ('pif_refresh_summary', None),
 ('pif_refreshing', None), ('pif_refresh_ok', None), ('pif_refresh_failed', None),
 ('pif_clear_title', None), ('pif_clear_summary', None),
 ('pif_clear_confirm', None), ('pif_cleared', None),
]
ARRAYS = ['game_level_entries', 'game_cpu_level_summaries', 'game_gpu_level_summaries',
          'cooldown_entries', 'cooldown_values']

L = {}
L['en'] = dict(
 app_name='Custom Tweaks',
 app_summary='Game performance tuning, Play Integrity settings',
 game_perf_title='Game performance',
 game_perf_on='On',
 game_perf_off='Off',
 game_perf_main_switch='Use per-app CPU and GPU settings',
 game_mem_clean_title='Free memory for games',
 game_mem_clean_summary='Closes background apps when an app from the list opens',
 game_apps_category='Apps',
 game_app_add='Add app',
 game_app_remove='Remove from list',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='Settings apply only while the app is on screen. Clocks return to normal when you leave the app. Thermal protection always stays active.',
 game_custom_cpu_title='CPU clock',
 game_custom_gpu_title='GPU limit',
 game_custom_range_summary='30–100 %',
 game_custom_cpu_summary='Custom %1$d%%',
 game_custom_gpu_summary='Custom %1$d%%',
 game_custom_level='Custom',
 play_store_category='Play Store',
 installer_spoof_title='Report the Play Store as the installer',
 installer_spoof_summary='Other apps see the Play Store as the installer of sideloaded apps, so apps that require a Play install keep working (for example Notein). Applies immediately; off by default',
 reboot_title='Restart required',
 reboot_now='Restart',
 reboot_later='Later',
 integrity_fix_title='Play Integrity Fix',
 integrity_fix_summary='Keybox renewal, TEE Simulator and PIF in one switch; takes effect after a restart',
 integrity_settings_title='Play Integrity Fix settings',
 integrity_settings_summary='Keybox status and renewal, TEE Simulator targets, PIF',
 cooldown_category='Automatic checks',
 check_period_title='Check interval',
 unlock_cooldown_title='Unlock cooldown',
 teesim_title='TEE Simulator',
 pif_title='PIF',
 integrity_reboot_message='This change is applied after the tablet restarts. Restart now?',
 integrity_reboot_off_message='Turning this off takes effect after the tablet restarts, and data that belongs to the feature (keyboxes, target list, pif.json) is removed then. Restart now?',
 integrity_status_category='Status',
 keybox_state_title='Keybox',
 keybox_state_installed='Installed',
 keybox_state_none='Not installed',
 keybox_state_unavailable='Service unavailable',
 keybox_state_revoked='Revoked by Google',
 keybox_source_title='Source',
 keybox_serial_title='Serial',
 keybox_auto_title='Automatic renewal',
 keybox_auto_summary='Checks the keybox catalog periodically and installs a fresh keybox; updates apply immediately',
 keybox_auto_rotate_title='Replace automatically when revoked',
 keybox_auto_rotate_summary='Swaps in the spare and fetches a fresh keybox when Google revokes the active one; off means only "Renew now" replaces it',
 keybox_renew_title='Renew now',
 keybox_renew_summary='Fetches the catalog and installs a keybox that is not revoked',
 keybox_renewing='Renewing…',
 keybox_renew_ok='Keybox installed: %1$s %2$s',
 keybox_renew_failed='Keybox renewal failed',
 keybox_clear_title='Delete keybox',
 keybox_clear_summary='Removes the installed keybox from the system',
 keybox_clear_confirm='Delete the installed keybox and all spare keyboxes? Hardware attestation is not spoofed until a new keybox is installed.',
 keybox_cleared='Keybox deleted',
 keybox_pool_title='Spare keyboxes',
 keybox_pool_summary='%1$d spare, %2$d revoked serials on record',
 keybox_pool_none='None',
 teesim_state_title='TEE Simulator',
 teesim_on='On',
 teesim_off='Off',
 teesim_keybox_title='Keybox',
 teesim_targets_category='Target apps',
 teesim_targets_all='All apps',
 teesim_targets_all_summary='Spoofs the attestation of every app; turn it off to patch only the list below',
 teesim_target_add='Add app',
 teesim_target_remove='Tap to remove',
 teesim_target_remove_confirm='Remove this app from the target list?',
 teesim_auto_category='Automatic',
 teesim_auto_title='Add new apps automatically',
 teesim_auto_summary='Newly installed apps join the target list, uninstalled ones are dropped; checked on install and every five minutes',
 teesim_add_all='Add all installed apps',
 teesim_add_all_summary='Adds every third-party app that is installed right now',
 teesim_add_all_done='%1$d apps added',
 pif_state_title='pif.json status',
 pif_state_none='Not set',
 pif_state_user='User provided',
 pif_state_fetched='Fetched automatically',
 pif_patch_title='Security patch',
 pif_fingerprint_title='pif.json',
 pif_refresh_title='Fetch now',
 pif_refresh_summary='Downloads the certified build properties immediately',
 pif_refreshing='Fetching…',
 pif_refresh_ok='pif.json updated',
 pif_refresh_failed='Fetch failed',
 pif_clear_title='Delete pif.json',
 pif_clear_summary='Removes the fetched pif.json data',
 pif_clear_confirm='Delete pif.json?',
 pif_cleared='pif.json deleted',
 game_perf_summary='CPU and GPU profiles per app; settings apply only while the app is on screen',

 game_level_entries=['Power saving', 'Balanced', 'Default'],

 cooldown_entries=['15 minutes', '30 minutes', '1 hour', '2 hours', '3 hours', '4 hours', '5 hours', '6 hours'],
 cooldown_values=['15', '30', '60', '120', '180', '240', '300', '360'],

 game_cpu_level_summaries=['Lower clocks for less heat and longer play time', 'Caps the single core and the other cores to about 80 % for steady long sessions', 'Stock clocks; thermal protection still applies', 'Set the single core and multi core limits yourself'],

 game_gpu_level_summaries=['Lower graphics clock for less heat', 'Caps the graphics clock to about 80 % for less heat in long sessions', 'Stock graphics clock', 'Set the graphics clock limit yourself'],

 keybox_manager_title='Keybox Manager',
)
L['ko'] = dict(
 app_name='커스텀 트윅',
 app_summary='게임 성능 조절, Play Integrity 설정',
 game_perf_title='게임 성능 관리',
 game_perf_on='사용',
 game_perf_off='사용 안함',
 game_perf_main_switch='앱별 CPU·GPU 설정 사용',
 game_mem_clean_title='게임용 메모리 정리',
 game_mem_clean_summary='목록의 앱을 열 때 백그라운드 앱을 종료합니다',
 game_apps_category='앱',
 game_app_add='앱 추가',
 game_app_remove='목록에서 삭제',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='설정은 해당 앱이 화면에 있을 때만 적용됩니다. 앱에서 나가면 클럭이 원래대로 돌아옵니다. 발열 보호는 항상 동작합니다.',
 game_custom_cpu_title='CPU 클럭',
 game_custom_gpu_title='GPU 제한',
 game_custom_range_summary='30~100%',
 game_custom_cpu_summary='사용자 설정 %1$d%%',
 game_custom_gpu_summary='사용자 설정 %1$d%%',
 game_custom_level='사용자 설정',
 play_store_category='Play 스토어',
 installer_spoof_title='Play 스토어에서 설치한 것으로 표시',
 installer_spoof_summary='다른 앱에 설치자를 Play 스토어로 알려줍니다. Play 설치가 필요한 앱(예: Notein)이 작동합니다. 즉시 적용되며 기본값은 꺼짐입니다',
 reboot_title='재시작 필요',
 reboot_now='다시 시작',
 reboot_later='나중에',
 integrity_fix_title='Play Integrity Fix',
 integrity_fix_summary='키박스 자동 갱신, TEE Simulator, PIF를 한 스위치로 켭니다. 다시 시작한 뒤 적용됩니다',
 integrity_settings_title='Play Integrity Fix 설정',
 integrity_settings_summary='키박스 상태·갱신, TEE Simulator 대상, PIF',
 cooldown_category='자동 점검',
 check_period_title='체크 주기',
 unlock_cooldown_title='잠금 해제 쿨타임',
 teesim_title='TEE Simulator',
 pif_title='PIF',
 integrity_reboot_message='이 변경은 태블릿을 다시 시작한 뒤 적용됩니다. 지금 다시 시작할까요?',
 integrity_reboot_off_message='기능을 끄면 다시 시작한 뒤 꺼지고, 그때 관련 데이터(키박스, 대상 목록, pif.json)가 삭제됩니다. 지금 다시 시작할까요?',
 integrity_status_category='상태',
 keybox_state_title='키박스',
 keybox_state_installed='설치됨',
 keybox_state_none='설치 안 됨',
 keybox_state_unavailable='서비스를 사용할 수 없음',
 keybox_state_revoked='Google에서 폐기됨',
 keybox_source_title='출처',
 keybox_serial_title='일련번호',
 keybox_auto_title='자동 갱신',
 keybox_auto_summary='주기적으로 키박스 카탈로그를 확인해 새 키박스를 설치합니다. 갱신은 즉시 적용됩니다',
 keybox_auto_rotate_title='폐기되면 자동 교체',
 keybox_auto_rotate_summary='Google이 활성 키박스를 폐기하면 보관된 예비로 즉시 교체하고 새 키박스를 받아둡니다. 끄면 "지금 갱신"으로만 교체됩니다',
 keybox_renew_title='지금 갱신',
 keybox_renew_summary='카탈로그에서 폐기되지 않은 키박스를 받아 설치합니다',
 keybox_renewing='갱신 중…',
 keybox_renew_ok='키박스 설치됨: %1$s %2$s',
 keybox_renew_failed='키박스 갱신 실패',
 keybox_clear_title='키박스 삭제',
 keybox_clear_summary='설치된 키박스를 시스템에서 제거합니다',
 keybox_clear_confirm='설치된 키박스와 보관된 예비 키박스를 모두 삭제할까요? 새 키박스를 설치할 때까지 하드웨어 키 증명이 위장되지 않습니다.',
 keybox_cleared='키박스를 삭제했습니다',
 keybox_pool_title='보관된 키박스',
 keybox_pool_summary='%1$d개 보관 · 폐기 기록 %2$d건',
 keybox_pool_none='없음',
 teesim_state_title='TEE Simulator',
 teesim_on='사용',
 teesim_off='사용 안 함',
 teesim_keybox_title='키박스',
 teesim_targets_category='대상 앱',
 teesim_targets_all='모든 앱',
 teesim_targets_all_summary='모든 앱의 증명을 위장합니다. 끄면 아래 목록만 패치합니다',
 teesim_target_add='앱 추가',
 teesim_target_remove='눌러서 삭제',
 teesim_target_remove_confirm='이 앱을 대상 목록에서 삭제할까요?',
 teesim_auto_category='자동 관리',
 teesim_auto_title='새 앱 자동 추가',
 teesim_auto_summary='새로 설치된 앱이 대상 목록에 추가되고 삭제된 앱은 제거됩니다. 설치 시 즉시, 이후 5분마다 확인합니다',
 teesim_add_all='설치된 앱 모두 추가',
 teesim_add_all_summary='지금 설치된 모든 서드파티 앱을 대상 목록에 추가합니다',
 teesim_add_all_done='%1$d개 앱을 추가했습니다',
 pif_state_title='pif.json 상태',
 pif_state_none='없음',
 pif_state_user='사용자 제공',
 pif_state_fetched='자동으로 받음',
 pif_patch_title='보안 패치',
 pif_fingerprint_title='pif.json',
 pif_refresh_title='지금 받기',
 pif_refresh_summary='인증된 빌드 속성을 즉시 내려받습니다',
 pif_refreshing='받는 중…',
 pif_refresh_ok='pif.json을 갱신했습니다',
 pif_refresh_failed='받기 실패',
 pif_clear_title='pif.json 삭제',
 pif_clear_summary='받은 pif.json 데이터를 제거합니다',
 pif_clear_confirm='pif.json을 삭제할까요?',
 pif_cleared='pif.json을 삭제했습니다',
 game_perf_summary='앱별 CPU·GPU 설정입니다. 설정은 해당 앱이 화면에 있을 때만 적용됩니다',

 game_level_entries=['절전', '균형', '기본값'],

 cooldown_entries=['15분', '30분', '1시간', '2시간', '3시간', '4시간', '5시간', '6시간'],
 cooldown_values=['15', '30', '60', '120', '180', '240', '300', '360'],

 game_cpu_level_summaries=['클럭을 낮춰 발열을 줄이고 플레이 시간을 늘립니다', '싱글 코어와 나머지 코어를 약 80%로 제한해 오래 플레이해도 안정적입니다', '순정 클럭을 사용합니다 (발열 보호는 유지)', '싱글·멀티 코어 제한을 직접 설정합니다'],

 game_gpu_level_summaries=['그래픽 클럭을 낮춰 발열을 줄입니다', '그래픽 클럭을 약 80%로 제한해 오래 플레이할 때 발열을 줄입니다', '순정 그래픽 클럭을 사용합니다', 'GPU 클럭 제한을 직접 설정합니다'],

)
L['ja'] = dict(
 app_name='Custom Tweaks',
 app_summary='ゲームパフォーマンス調整、Play Integrity 設定',
 game_perf_title='ゲームパフォーマンス',
 game_perf_on='オン',
 game_perf_off='オフ',
 game_perf_main_switch='アプリ別のパフォーマンスプロファイルを使用',
 game_mem_clean_title='ゲーム用にメモリを解放',
 game_mem_clean_summary='リストのアプリを開くとバックグラウンドアプリを終了します',
 game_apps_category='アプリ',
 game_app_add='アプリを追加',
 game_app_remove='削除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='プロファイルはそのアプリが画面に表示されている間だけ適用されます。アプリを離れるとクロックは元に戻ります。熱保護は常に有効です。',
 game_custom_cpu_title='CPUクロック',
 game_custom_gpu_title='GPU制限',
 game_custom_range_summary='30～100%',
 game_custom_cpu_summary='カスタム %1$d%%',
 game_custom_gpu_summary='カスタム %1$d%%',
 game_custom_level='カスタム',
 play_store_category='Play ストア',
 reboot_title='再起動が必要です',
 reboot_now='再起動',
 reboot_later='後で',
 game_perf_summary='アプリ別のCPU・GPU設定です。設定はアプリが画面に表示されている間だけ適用されます',

 game_level_entries=['省電力', 'バランス', 'デフォルト'],

 game_cpu_level_summaries=['クロックを下げて発熱を抑え、プレイ時間を延ばします', 'シングルコアとその他のコアを約80%に制限し、長時間でも安定させます', '標準のクロックを使用します（熱保護は有効）', 'シングルコアとマルチコアの制限を自分で設定します'],

 game_gpu_level_summaries=['グラフィッククロックを下げて発熱を抑えます', 'グラフィッククロックを約80%に制限し、長時間でも安定させます', '標準のグラフィッククロックを使用します', 'グラフィッククロックの制限を自分で設定します'],

 installer_spoof_title='Play ストアからのインストールとして表示',
 installer_spoof_summary='サイドロードしたアプリのインストーラーを Play ストアとして他のアプリに通知します。Play からのインストールが必要なアプリ（例: Notein）が動作します。すぐに適用され、初期値はオフです',
 integrity_fix_summary='Keybox の更新、TEE Simulator、PIF を 1 つのスイッチで有効にします。再起動後に適用されます',
 integrity_settings_title='Play Integrity Fix の設定',
 integrity_settings_summary='Keybox の状態と更新、TEE Simulator の対象、PIF',
 cooldown_category='自動チェック',
 check_period_title='チェック間隔',
 unlock_cooldown_title='ロック解除のクールダウン',
 keybox_state_installed='インストール済み',
 keybox_state_none='未インストール',
 keybox_state_unavailable='サービスを利用できません',
 keybox_state_revoked='Google により失効',
 keybox_source_title='ソース',
 keybox_serial_title='シリアル',
 keybox_auto_title='自動更新',
 keybox_auto_summary='定期的に Keybox カタログを確認して新しい Keybox をインストールします。更新はすぐに適用されます',
 keybox_auto_rotate_title='失効時に自動で交換',
 keybox_auto_rotate_summary='Google が有効な Keybox を失効させたら、予備と交換して新しい Keybox を取得します。オフの場合は「今すぐ更新」のみが交換します',
 keybox_renew_title='今すぐ更新',
 keybox_renew_summary='カタログから失効していない Keybox を取得してインストールします',
 keybox_renewing='更新中…',
 keybox_renew_ok='Keybox をインストールしました: %1$s %2$s',
 keybox_renew_failed='Keybox の更新に失敗しました',
 keybox_clear_title='Keybox を削除',
 keybox_clear_summary='インストールされた Keybox をシステムから削除します',
 keybox_clear_confirm='インストールされた Keybox とすべての予備 Keybox を削除しますか？新しい Keybox をインストールするまでハードウェア認証は偽装されません。',
 keybox_cleared='Keybox を削除しました',
 keybox_pool_title='予備の Keybox',
 keybox_pool_summary='予備 %1$d 個、失効記録 %2$d 件',
 keybox_pool_none='なし',
 teesim_on='オン',
 teesim_off='オフ',
 teesim_targets_category='対象アプリ',
 teesim_targets_all='すべてのアプリ',
 teesim_targets_all_summary='すべてのアプリの認証を偽装します。オフにすると下のリストのみを対象にします',
 teesim_target_add='アプリを追加',
 teesim_target_remove='タップして削除',
 teesim_target_remove_confirm='このアプリを対象リストから削除しますか？',
 teesim_auto_category='自動',
 teesim_auto_title='新しいアプリを自動追加',
 teesim_auto_summary='新しくインストールしたアプリを対象リストに追加し、アンインストールしたアプリは除外します。インストール時と 5 分ごとに確認します',
 teesim_add_all='インストール済みアプリをすべて追加',
 teesim_add_all_summary='現在インストールされているすべてのサードパーティ製アプリを追加します',
 teesim_add_all_done='%1$d 個のアプリを追加しました',
 pif_state_title='pif.json の状態',
 pif_state_none='未設定',
 pif_state_user='ユーザー提供',
 pif_state_fetched='自動取得',
 pif_patch_title='セキュリティパッチ',
 pif_refresh_title='今すぐ取得',
 pif_refresh_summary='認定されたビルドプロパティをすぐにダウンロードします',
 pif_refreshing='取得中…',
 pif_refresh_ok='pif.json を更新しました',
 pif_refresh_failed='取得に失敗しました',
 pif_clear_title='pif.json を削除',
 pif_clear_summary='取得した pif.json データを削除します',
 pif_clear_confirm='pif.json を削除しますか？',
 pif_cleared='pif.json を削除しました',
 integrity_reboot_message='この変更はタブレットの再起動後に適用されます。今すぐ再起動しますか？',
 integrity_reboot_off_message='オフにすると再起動後に適用され、そのとき関連データ（Keybox、対象リスト、pif.json）が削除されます。今すぐ再起動しますか？',
 cooldown_entries=['15分', '30分', '1時間', '2時間', '3時間', '4時間', '5時間', '6時間'],
)
L['zh-rCN'] = dict(
 app_name='Custom Tweaks',
 app_summary='游戏性能调节、Play Integrity 设置',
 game_perf_title='游戏性能',
 game_perf_on='开启',
 game_perf_off='关闭',
 game_perf_main_switch='使用应用性能配置',
 game_mem_clean_title='游戏内存清理',
 game_mem_clean_summary='打开列表中的应用时关闭后台应用',
 game_apps_category='应用',
 game_app_add='添加应用',
 game_app_remove='移除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='配置仅在对应应用显示在屏幕上时生效，离开应用后频率恢复正常。温控保护始终有效。',
 game_custom_cpu_title='CPU 频率',
 game_custom_gpu_title='GPU 限制',
 game_custom_range_summary='30～100%',
 game_custom_cpu_summary='自定义 %1$d%%',
 game_custom_gpu_summary='自定义 %1$d%%',
 game_custom_level='自定义',
 play_store_category='Play 商店',
 reboot_title='需要重启',
 reboot_now='重启',
 reboot_later='稍后',
 game_perf_summary='按应用设置CPU和GPU；设置仅在该应用显示时生效',

 game_level_entries=['省电', '均衡', '默认'],

 game_cpu_level_summaries=['降低频率，减少发热，延长游戏时间', '将单核和其他核心限制在约 80%，长时间游戏更稳定', '使用原厂频率（温控仍然有效）', '自行设置单核和多核限制'],

 game_gpu_level_summaries=['降低图形频率，减少发热', '将图形频率限制在约 80%，长时间更稳定', '使用原厂图形频率', '自行设置图形频率限制'],

 installer_spoof_title='将安装来源显示为 Play 商店',
 installer_spoof_summary='向其他应用显示侧载应用来自 Play 商店安装，因此需要 Play 安装的应用（例如 Notein）可以正常工作。立即生效，默认关闭',
 integrity_fix_summary='用一个开关启用 Keybox 更新、TEE Simulator 和 PIF；重启后生效',
 integrity_settings_title='Play Integrity Fix 设置',
 integrity_settings_summary='Keybox 状态与更新、TEE Simulator 目标、PIF',
 cooldown_category='自动检查',
 check_period_title='检查间隔',
 unlock_cooldown_title='解锁冷却时间',
 keybox_state_installed='已安装',
 keybox_state_none='未安装',
 keybox_state_unavailable='服务不可用',
 keybox_state_revoked='已被 Google 吊销',
 keybox_source_title='来源',
 keybox_serial_title='序列号',
 keybox_auto_title='自动更新',
 keybox_auto_summary='定期检查 Keybox 目录并安装新的 Keybox；更新立即生效',
 keybox_auto_rotate_title='吊销时自动更换',
 keybox_auto_rotate_summary='当 Google 吊销当前 Keybox 时，换用备用并获取新的 Keybox；关闭后只能通过“立即更新”更换',
 keybox_renew_title='立即更新',
 keybox_renew_summary='从目录获取未吊销的 Keybox 并安装',
 keybox_renewing='更新中…',
 keybox_renew_ok='已安装 Keybox：%1$s %2$s',
 keybox_renew_failed='Keybox 更新失败',
 keybox_clear_title='删除 Keybox',
 keybox_clear_summary='从系统中删除已安装的 Keybox',
 keybox_clear_confirm='删除已安装的 Keybox 和所有备用 Keybox？在安装新的 Keybox 之前，硬件认证不会被伪装。',
 keybox_cleared='已删除 Keybox',
 keybox_pool_title='备用 Keybox',
 keybox_pool_summary='备用 %1$d 个，吊销记录 %2$d 条',
 keybox_pool_none='无',
 teesim_on='开启',
 teesim_off='关闭',
 teesim_targets_category='目标应用',
 teesim_targets_all='所有应用',
 teesim_targets_all_summary='伪装所有应用的认证；关闭后只处理下面的列表',
 teesim_target_add='添加应用',
 teesim_target_remove='点击移除',
 teesim_target_remove_confirm='将此应用从目标列表移除？',
 teesim_auto_category='自动',
 teesim_auto_title='自动添加新应用',
 teesim_auto_summary='新安装的应用会加入目标列表，卸载的应用会被移除；安装时和每 5 分钟检查一次',
 teesim_add_all='添加所有已安装应用',
 teesim_add_all_summary='添加当前安装的所有第三方应用',
 teesim_add_all_done='已添加 %1$d 个应用',
 pif_state_title='pif.json 状态',
 pif_state_none='未设置',
 pif_state_user='用户提供',
 pif_state_fetched='自动获取',
 pif_patch_title='安全补丁',
 pif_refresh_title='立即获取',
 pif_refresh_summary='立即下载认证的构建属性',
 pif_refreshing='获取中…',
 pif_refresh_ok='pif.json 已更新',
 pif_refresh_failed='获取失败',
 pif_clear_title='删除 pif.json',
 pif_clear_summary='删除已获取的 pif.json 数据',
 pif_clear_confirm='删除 pif.json？',
 pif_cleared='已删除 pif.json',
 integrity_reboot_message='此更改将在平板电脑重启后生效。现在重启吗？',
 integrity_reboot_off_message='关闭后将在重启时生效，届时相关数据（Keybox、目标列表、pif.json）会被删除。现在重启吗？',
 cooldown_entries=['15 分钟', '30 分钟', '1 小时', '2 小时', '3 小时', '4 小时', '5 小时', '6 小时'],
)
L['zh-rTW'] = dict(
 app_name='Custom Tweaks',
 app_summary='遊戲效能調整、Play Integrity 設定',
 game_perf_title='遊戲效能',
 game_perf_on='開啟',
 game_perf_off='關閉',
 game_perf_main_switch='使用應用程式效能設定檔',
 game_mem_clean_title='遊戲記憶體清理',
 game_mem_clean_summary='開啟清單中的應用程式時關閉背景應用程式',
 game_apps_category='應用程式',
 game_app_add='新增應用程式',
 game_app_remove='移除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='設定檔僅在該應用程式顯示於螢幕上時生效，離開後時脈恢復正常。溫度保護始終有效。',
 game_custom_cpu_title='CPU 時脈',
 game_custom_gpu_title='GPU 限制',
 game_custom_range_summary='30～100%',
 game_custom_cpu_summary='自訂 %1$d%%',
 game_custom_gpu_summary='自訂 %1$d%%',
 game_custom_level='自訂',
 play_store_category='Play 商店',
 reboot_title='需要重新啟動',
 reboot_now='重新啟動',
 reboot_later='稍後',
 game_perf_summary='依應用設定CPU與GPU；設定僅在該應用顯示時生效',

 game_level_entries=['省電', '平衡', '預設'],

 game_cpu_level_summaries=['降低時脈，減少發熱，延長遊戲時間', '將單核與其他核心限制在約 80%，長時間遊戲更穩定', '使用原廠時脈（溫度保護仍有效）', '自行設定單核與多核限制'],

 game_gpu_level_summaries=['降低圖形時脈，減少發熱', '將圖形時脈限制在約 80%，長時間更穩定', '使用原廠圖形時脈', '自行設定圖形時脈限制'],

 installer_spoof_title='將安裝來源顯示為 Play 商店',
 installer_spoof_summary='向其他應用程式顯示側載應用程式來自 Play 商店安裝，因此需要 Play 安裝的應用程式（例如 Notein）可以正常運作。立即生效，預設關閉',
 integrity_fix_summary='用一個開關啟用 Keybox 更新、TEE Simulator 和 PIF；重新啟動後生效',
 integrity_settings_title='Play Integrity Fix 設定',
 integrity_settings_summary='Keybox 狀態與更新、TEE Simulator 目標、PIF',
 cooldown_category='自動檢查',
 check_period_title='檢查間隔',
 unlock_cooldown_title='解鎖冷卻時間',
 keybox_state_installed='已安裝',
 keybox_state_none='未安裝',
 keybox_state_unavailable='服務無法使用',
 keybox_state_revoked='已被 Google 撤銷',
 keybox_source_title='來源',
 keybox_serial_title='序號',
 keybox_auto_title='自動更新',
 keybox_auto_summary='定期檢查 Keybox 目錄並安裝新的 Keybox；更新立即生效',
 keybox_auto_rotate_title='撤銷時自動更換',
 keybox_auto_rotate_summary='當 Google 撤銷目前的 Keybox 時，換用備用並取得新的 Keybox；關閉後只能透過「立即更新」更換',
 keybox_renew_title='立即更新',
 keybox_renew_summary='從目錄取得未撤銷的 Keybox 並安裝',
 keybox_renewing='更新中…',
 keybox_renew_ok='已安裝 Keybox：%1$s %2$s',
 keybox_renew_failed='Keybox 更新失敗',
 keybox_clear_title='刪除 Keybox',
 keybox_clear_summary='從系統中刪除已安裝的 Keybox',
 keybox_clear_confirm='刪除已安裝的 Keybox 與所有備用 Keybox？在安裝新的 Keybox 之前，硬體認證不會被偽裝。',
 keybox_cleared='已刪除 Keybox',
 keybox_pool_title='備用 Keybox',
 keybox_pool_summary='備用 %1$d 個，撤銷記錄 %2$d 筆',
 keybox_pool_none='無',
 teesim_on='開啟',
 teesim_off='關閉',
 teesim_targets_category='目標應用程式',
 teesim_targets_all='所有應用程式',
 teesim_targets_all_summary='偽裝所有應用程式的認證；關閉後只處理下面的清單',
 teesim_target_add='新增應用程式',
 teesim_target_remove='點一下移除',
 teesim_target_remove_confirm='將此應用程式從目標清單移除？',
 teesim_auto_category='自動',
 teesim_auto_title='自動新增應用程式',
 teesim_auto_summary='新安裝的應用程式會加入目標清單，解除安裝的會移除；安裝時與每 5 分鐘檢查一次',
 teesim_add_all='新增所有已安裝應用程式',
 teesim_add_all_summary='新增目前安裝的所有第三方應用程式',
 teesim_add_all_done='已新增 %1$d 個應用程式',
 pif_state_title='pif.json 狀態',
 pif_state_none='未設定',
 pif_state_user='使用者提供',
 pif_state_fetched='自動取得',
 pif_patch_title='安全性修補',
 pif_refresh_title='立即取得',
 pif_refresh_summary='立即下載認證的建置屬性',
 pif_refreshing='取得中…',
 pif_refresh_ok='pif.json 已更新',
 pif_refresh_failed='取得失敗',
 pif_clear_title='刪除 pif.json',
 pif_clear_summary='刪除已取得的 pif.json 資料',
 pif_clear_confirm='刪除 pif.json？',
 pif_cleared='已刪除 pif.json',
 integrity_reboot_message='此變更將於平板電腦重新啟動後生效。要立即重新啟動嗎？',
 integrity_reboot_off_message='關閉後將於重新啟動時生效，屆時相關資料（Keybox、目標清單、pif.json）會被刪除。要立即重新啟動嗎？',
 cooldown_entries=['15 分鐘', '30 分鐘', '1 小時', '2 小時', '3 小時', '4 小時', '5 小時', '6 小時'],
)
L['de'] = dict(
 app_name='Custom Tweaks',
 app_summary='Spielleistungsanpassung, Play-Integrity-Einstellungen',
 game_perf_title='Spieleleistung',
 game_perf_on='An',
 game_perf_off='Aus',
 game_perf_main_switch='Leistungsprofile pro App verwenden',
 game_mem_clean_title='Speicher für Spiele freigeben',
 game_mem_clean_summary='Schließt Hintergrund-Apps, wenn eine App aus der Liste geöffnet wird',
 game_apps_category='Apps',
 game_app_add='App hinzufügen',
 game_app_remove='Entfernen',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='Ein Profil gilt nur, solange seine App auf dem Bildschirm ist. Beim Verlassen der App kehren die Taktraten zum Normalwert zurück. Der Überhitzungsschutz bleibt immer aktiv.',
 game_custom_cpu_title='CPU-Takt',
 game_custom_gpu_title='GPU-Limit',
 game_custom_range_summary='30–100 %',
 game_custom_cpu_summary='Benutzerdefiniert %1$d%%',
 game_custom_gpu_summary='Benutzerdefiniert %1$d%%',
 game_custom_level='Benutzerdefiniert',
 play_store_category='Play Store',
 reboot_title='Neustart erforderlich',
 reboot_now='Neu starten',
 reboot_later='Später',
 game_perf_summary='CPU- und GPU-Profile pro App; die Einstellungen gelten nur, solange die App sichtbar ist',

 game_level_entries=['Energiesparen', 'Ausgewogen', 'Standard'],

 game_cpu_level_summaries=['Niedrigere Taktraten für weniger Wärme und längere Spielzeit', 'Begrenzt den Einzelkern und die übrigen Kerne auf etwa 80 % für lange, stabile Sitzungen', 'Serienmäßige Taktraten; Überhitzungsschutz bleibt aktiv', 'Einzel- und Mehrkern-Limit selbst festlegen'],

 game_gpu_level_summaries=['Niedrigerer Grafiktakt für weniger Wärme', 'Begrenzter Grafiktakt auf etwa 80 % für lange, stabile Sitzungen', 'Serienmäßiger Grafiktakt', 'Grafiktakt-Limit selbst festlegen'],

 installer_spoof_title='Play Store als Installationsquelle melden',
 installer_spoof_summary='Andere Apps sehen den Play Store als Installationsquelle von per Sideload installierten Apps, damit Apps, die eine Play-Installation verlangen (zum Beispiel Notein), weiter funktionieren. Gilt sofort; standardmäßig aus',
 integrity_fix_summary='Keybox-Erneuerung, TEE Simulator und PIF in einem Schalter; wirkt nach einem Neustart',
 integrity_settings_title='Play Integrity Fix-Einstellungen',
 integrity_settings_summary='Keybox-Status und -Erneuerung, TEE-Simulator-Ziele, PIF',
 cooldown_category='Automatische Prüfungen',
 check_period_title='Prüfintervall',
 unlock_cooldown_title='Entsperrungs-Cooldown',
 keybox_state_installed='Installiert',
 keybox_state_none='Nicht installiert',
 keybox_state_unavailable='Dienst nicht verfügbar',
 keybox_state_revoked='Von Google widerrufen',
 keybox_source_title='Quelle',
 keybox_serial_title='Seriennummer',
 keybox_auto_title='Automatische Erneuerung',
 keybox_auto_summary='Prüft regelmäßig den Keybox-Katalog und installiert eine neue Keybox; Aktualisierungen gelten sofort',
 keybox_auto_rotate_title='Bei Widerruf automatisch ersetzen',
 keybox_auto_rotate_summary='Tauscht den Ersatz ein und lädt eine neue Keybox, wenn Google die aktive widerruft; aus bedeutet, nur „Jetzt erneuern“ ersetzt sie',
 keybox_renew_title='Jetzt erneuern',
 keybox_renew_summary='Lädt den Katalog und installiert eine nicht widerrufene Keybox',
 keybox_renewing='Wird erneuert…',
 keybox_renew_ok='Keybox installiert: %1$s %2$s',
 keybox_renew_failed='Keybox-Erneuerung fehlgeschlagen',
 keybox_clear_title='Keybox löschen',
 keybox_clear_summary='Entfernt die installierte Keybox aus dem System',
 keybox_clear_confirm='Installierte Keybox und alle Ersatz-Keyboxes löschen? Die Hardware-Attestierung wird erst mit einer neuen Keybox vorgetäuscht.',
 keybox_cleared='Keybox gelöscht',
 keybox_pool_title='Ersatz-Keyboxes',
 keybox_pool_summary='%1$d Ersatz, %2$d widerrufene Seriennummern gespeichert',
 keybox_pool_none='Keine',
 teesim_on='An',
 teesim_off='Aus',
 teesim_targets_category='Ziel-Apps',
 teesim_targets_all='Alle Apps',
 teesim_targets_all_summary='Täuscht die Attestierung jeder App vor; ausschalten, um nur die Liste unten zu bearbeiten',
 teesim_target_add='App hinzufügen',
 teesim_target_remove='Zum Entfernen tippen',
 teesim_target_remove_confirm='Diese App aus der Ziellaiste entfernen?',
 teesim_auto_category='Automatisch',
 teesim_auto_title='Neue Apps automatisch hinzufügen',
 teesim_auto_summary='Neu installierte Apps kommen in die Ziellaiste, deinstallierte werden entfernt; Prüfung bei Installation und alle fünf Minuten',
 teesim_add_all='Alle installierten Apps hinzufügen',
 teesim_add_all_summary='Fügt jede jetzt installierte Drittanbieter-App hinzu',
 teesim_add_all_done='%1$d Apps hinzugefügt',
 pif_state_title='pif.json-Status',
 pif_state_none='Nicht gesetzt',
 pif_state_user='Vom Nutzer bereitgestellt',
 pif_state_fetched='Automatisch geladen',
 pif_patch_title='Sicherheitspatch',
 pif_refresh_title='Jetzt laden',
 pif_refresh_summary='Lädt die zertifizierten Build-Eigenschaften sofort herunter',
 pif_refreshing='Wird geladen…',
 pif_refresh_ok='pif.json aktualisiert',
 pif_refresh_failed='Laden fehlgeschlagen',
 pif_clear_title='pif.json löschen',
 pif_clear_summary='Entfernt die geladenen pif.json-Daten',
 pif_clear_confirm='pif.json löschen?',
 pif_cleared='pif.json gelöscht',
 integrity_reboot_message='Diese Änderung gilt nach einem Neustart des Tablets. Jetzt neu starten?',
 integrity_reboot_off_message='Beim Ausschalten gilt sie nach einem Neustart, dabei werden die zugehörigen Daten (Keyboxes, Ziellaiste, pif.json) entfernt. Jetzt neu starten?',
 cooldown_entries=['15 Minuten', '30 Minuten', '1 Stunde', '2 Stunden', '3 Stunden', '4 Stunden', '5 Stunden', '6 Stunden'],
)
L['fr'] = dict(
 app_name='Custom Tweaks',
 app_summary='Réglage des performances de jeu, paramètres Play Integrity',
 game_perf_title='Performances en jeu',
 game_perf_on='Activé',
 game_perf_off='Désactivé',
 game_perf_main_switch='Utiliser des profils de performances par application',
 game_mem_clean_title='Libérer la mémoire pour les jeux',
 game_mem_clean_summary="Ferme les applications en arrière-plan à l'ouverture d'une application de la liste",
 game_apps_category='Applications',
 game_app_add='Ajouter une application',
 game_app_remove='Retirer',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer="Un profil ne s'applique que lorsque son application est à l'écran. Les fréquences reviennent à la normale quand vous la quittez. La protection thermique reste toujours active.",
 game_custom_cpu_title='Fréquence du CPU',
 game_custom_gpu_title='Limite GPU',
 game_custom_range_summary='30–100 %',
 game_custom_cpu_summary='Personnalisé %1$d%%',
 game_custom_gpu_summary='Personnalisé %1$d%%',
 game_custom_level='Personnalisé',
 play_store_category='Play Store',
 reboot_title='Redémarrage requis',
 reboot_now='Redémarrer',
 reboot_later='Plus tard',
 game_perf_summary="Profils CPU et GPU par application ; les réglages ne s'appliquent que lorsque l'application est à l'écran",

 game_level_entries=["Économie d'énergie", 'Équilibré', 'Par défaut'],

 game_cpu_level_summaries=["Fréquences réduites pour moins de chaleur et plus d'autonomie", 'Limite le cœur principal et les autres cœurs à environ 80 % pour une fluidité durable', "Fréquences d'origine ; la protection thermique reste active", 'Définissez vous-même les limites simple et multiple'],

 game_gpu_level_summaries=['Fréquence graphique réduite pour moins de chaleur', 'Fréquence graphique limitée à environ 80 % pour une stabilité durable', "Fréquence graphique d'origine", 'Définissez vous-même la limite de fréquence graphique'],

 installer_spoof_title='Signaler le Play Store comme installateur',
 installer_spoof_summary='Les autres applications voient le Play Store comme installateur des applis installées hors Play, donc les applis qui exigent une installation Play (par exemple Notein) continuent de fonctionner. S’applique immédiatement, désactivé par défaut',
 integrity_fix_summary='Renouvellement de la Keybox, TEE Simulator et PIF dans un seul interrupteur ; prend effet après un redémarrage',
 integrity_settings_title='Paramètres de Play Integrity Fix',
 integrity_settings_summary='État et renouvellement de la Keybox, cibles du TEE Simulator, PIF',
 cooldown_category='Vérifications automatiques',
 check_period_title='Intervalle de vérification',
 unlock_cooldown_title='Délai après déverrouillage',
 keybox_state_installed='Installée',
 keybox_state_none='Non installée',
 keybox_state_unavailable='Service indisponible',
 keybox_state_revoked='Révoquée par Google',
 keybox_source_title='Source',
 keybox_serial_title='Numéro de série',
 keybox_auto_title='Renouvellement automatique',
 keybox_auto_summary='Vérifie régulièrement le catalogue de Keybox et installe une nouvelle Keybox ; les mises à jour s’appliquent immédiatement',
 keybox_auto_rotate_title='Remplacer automatiquement si révoquée',
 keybox_auto_rotate_summary='Utilise la Keybox de secours et en télécharge une nouvelle quand Google révoque l’active ; désactivé, seul « Renouveler maintenant » la remplace',
 keybox_renew_title='Renouveler maintenant',
 keybox_renew_summary='Télécharge le catalogue et installe une Keybox non révoquée',
 keybox_renewing='Renouvellement…',
 keybox_renew_ok='Keybox installée : %1$s %2$s',
 keybox_renew_failed='Échec du renouvellement de la Keybox',
 keybox_clear_title='Supprimer la Keybox',
 keybox_clear_summary='Supprime la Keybox installée du système',
 keybox_clear_confirm='Supprimer la Keybox installée et toutes les Keybox de secours ? L’attestation matérielle n’est plus simulée tant qu’une nouvelle Keybox n’est pas installée.',
 keybox_cleared='Keybox supprimée',
 keybox_pool_title='Keybox de secours',
 keybox_pool_summary='%1$d de secours, %2$d numéros révoqués enregistrés',
 keybox_pool_none='Aucune',
 teesim_on='Activé',
 teesim_off='Désactivé',
 teesim_targets_category='Applis ciblées',
 teesim_targets_all='Toutes les applis',
 teesim_targets_all_summary='Simule l’attestation de toutes les applis ; désactivez pour ne traiter que la liste ci-dessous',
 teesim_target_add='Ajouter une appli',
 teesim_target_remove='Toucher pour retirer',
 teesim_target_remove_confirm='Retirer cette appli de la liste ciblée ?',
 teesim_auto_category='Automatique',
 teesim_auto_title='Ajouter les nouvelles applis automatiquement',
 teesim_auto_summary='Les applis nouvellement installées rejoignent la liste ciblée, les désinstallées en sortent ; vérification à l’installation et toutes les cinq minutes',
 teesim_add_all='Ajouter toutes les applis installées',
 teesim_add_all_summary='Ajoute toutes les applis tierces installées actuellement',
 teesim_add_all_done='%1$d applis ajoutées',
 pif_state_title='État de pif.json',
 pif_state_none='Non défini',
 pif_state_user='Fourni par l’utilisateur',
 pif_state_fetched='Récupéré automatiquement',
 pif_patch_title='Correctif de sécurité',
 pif_refresh_title='Récupérer maintenant',
 pif_refresh_summary='Télécharge immédiatement les propriétés de build certifiées',
 pif_refreshing='Récupération…',
 pif_refresh_ok='pif.json mis à jour',
 pif_refresh_failed='Échec de la récupération',
 pif_clear_title='Supprimer pif.json',
 pif_clear_summary='Supprime les données pif.json récupérées',
 pif_clear_confirm='Supprimer pif.json ?',
 pif_cleared='pif.json supprimé',
 integrity_reboot_message='Cette modification s’applique après le redémarrage de la tablette. Redémarrer maintenant ?',
 integrity_reboot_off_message='La désactivation prend effet après un redémarrage, qui supprime aussi les données associées (Keybox, liste ciblée, pif.json). Redémarrer maintenant ?',
 cooldown_entries=['15 minutes', '30 minutes', '1 heure', '2 heures', '3 heures', '4 heures', '5 heures', '6 heures'],
)
L['es'] = dict(
 app_name='Custom Tweaks',
 app_summary='Ajuste del rendimiento en juegos, ajustes de Play Integrity',
 game_perf_title='Rendimiento en juegos',
 game_perf_on='Activado',
 game_perf_off='Desactivado',
 game_perf_main_switch='Usar perfiles de rendimiento por aplicación',
 game_mem_clean_title='Liberar memoria para juegos',
 game_mem_clean_summary='Cierra las aplicaciones en segundo plano al abrir una aplicación de la lista',
 game_apps_category='Aplicaciones',
 game_app_add='Añadir aplicación',
 game_app_remove='Quitar',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='Un perfil solo se aplica mientras su aplicación está en pantalla. Las frecuencias vuelven a la normalidad al salir de la aplicación. La protección térmica siempre sigue activa.',
 game_custom_cpu_title='Frecuencia de la CPU',
 game_custom_gpu_title='Límite de GPU',
 game_custom_range_summary='30–100 %',
 game_custom_cpu_summary='Personalizado %1$d%%',
 game_custom_gpu_summary='Personalizado %1$d%%',
 game_custom_level='Personalizado',
 play_store_category='Play Store',
 reboot_title='Reinicio necesario',
 reboot_now='Reiniciar',
 reboot_later='Más tarde',
 game_perf_summary='Perfiles de CPU y GPU por aplicación; los ajustes solo se aplican mientras la aplicación está en pantalla',

 game_level_entries=['Ahorro de energía', 'Equilibrado', 'Predeterminado'],

 game_cpu_level_summaries=['Frecuencias más bajas para menos calor y más tiempo de juego', 'Limita el núcleo principal y los demás a un 80 % para sesiones largas estables', 'Frecuencias originales; la protección térmica sigue activa', 'Define tú mismo los límites de uno y varios núcleos'],

 game_gpu_level_summaries=['Frecuencia gráfica más baja para menos calor', 'Frecuencia gráfica limitada a un 80 % para sesiones largas estables', 'Frecuencia gráfica original', 'Define tú mismo el límite de frecuencia gráfica'],

 installer_spoof_title='Mostrar Play Store como instalador',
 installer_spoof_summary='Otras apps ven Play Store como el instalador de las apps instaladas fuera de Play, así que las apps que exigen una instalación de Play (por ejemplo Notein) siguen funcionando. Se aplica al momento; desactivado por defecto',
 integrity_fix_summary='Renovación de la Keybox, TEE Simulator y PIF en un solo interruptor; surte efecto tras reiniciar',
 integrity_settings_title='Ajustes de Play Integrity Fix',
 integrity_settings_summary='Estado y renovación de la Keybox, destinos del TEE Simulator, PIF',
 cooldown_category='Comprobaciones automáticas',
 check_period_title='Intervalo de comprobación',
 unlock_cooldown_title='Espera tras desbloqueo',
 keybox_state_installed='Instalada',
 keybox_state_none='No instalada',
 keybox_state_unavailable='Servicio no disponible',
 keybox_state_revoked='Revocada por Google',
 keybox_source_title='Origen',
 keybox_serial_title='Número de serie',
 keybox_auto_title='Renovación automática',
 keybox_auto_summary='Comprueba el catálogo de Keybox periódicamente e instala una Keybox nueva; las actualizaciones se aplican al momento',
 keybox_auto_rotate_title='Reemplazar automáticamente al revocarse',
 keybox_auto_rotate_summary='Usa la Keybox de repuesto y descarga una nueva cuando Google revoca la activa; desactivado, solo «Renovar ahora» la reemplaza',
 keybox_renew_title='Renovar ahora',
 keybox_renew_summary='Descarga el catálogo e instala una Keybox no revocada',
 keybox_renewing='Renovando…',
 keybox_renew_ok='Keybox instalada: %1$s %2$s',
 keybox_renew_failed='Falló la renovación de la Keybox',
 keybox_clear_title='Eliminar Keybox',
 keybox_clear_summary='Elimina del sistema la Keybox instalada',
 keybox_clear_confirm='¿Eliminar la Keybox instalada y todas las de repuesto? La atestación de hardware no se simula hasta que se instale una nueva Keybox.',
 keybox_cleared='Keybox eliminada',
 keybox_pool_title='Keybox de repuesto',
 keybox_pool_summary='%1$d de repuesto, %2$d números revocados registrados',
 keybox_pool_none='Ninguna',
 teesim_on='Activado',
 teesim_off='Desactivado',
 teesim_targets_category='Apps objetivo',
 teesim_targets_all='Todas las apps',
 teesim_targets_all_summary='Simula la atestación de todas las apps; desactívalo para tratar solo la lista de abajo',
 teesim_target_add='Añadir app',
 teesim_target_remove='Toca para quitar',
 teesim_target_remove_confirm='¿Quitar esta app de la lista objetivo?',
 teesim_auto_category='Automático',
 teesim_auto_title='Añadir apps nuevas automáticamente',
 teesim_auto_summary='Las apps recién instaladas se añaden a la lista objetivo y las desinstaladas se quitan; se comprueba al instalar y cada cinco minutos',
 teesim_add_all='Añadir todas las apps instaladas',
 teesim_add_all_summary='Añade todas las apps de terceros instaladas ahora mismo',
 teesim_add_all_done='%1$d apps añadidas',
 pif_state_title='Estado de pif.json',
 pif_state_none='Sin definir',
 pif_state_user='Proporcionado por el usuario',
 pif_state_fetched='Obtenido automáticamente',
 pif_patch_title='Parche de seguridad',
 pif_refresh_title='Obtener ahora',
 pif_refresh_summary='Descarga las propiedades de compilación certificadas al momento',
 pif_refreshing='Obteniendo…',
 pif_refresh_ok='pif.json actualizado',
 pif_refresh_failed='Falló la obtención',
 pif_clear_title='Eliminar pif.json',
 pif_clear_summary='Elimina los datos de pif.json obtenidos',
 pif_clear_confirm='¿Eliminar pif.json?',
 pif_cleared='pif.json eliminado',
 integrity_reboot_message='Este cambio se aplica tras reiniciar la tablet. ¿Reiniciar ahora?',
 integrity_reboot_off_message='Al desactivarlo surte efecto tras reiniciar, y entonces se eliminan los datos asociados (Keybox, lista objetivo, pif.json). ¿Reiniciar ahora?',
 cooldown_entries=['15 minutos', '30 minutos', '1 hora', '2 horas', '3 horas', '4 horas', '5 horas', '6 horas'],
)
L['it'] = dict(
 app_name='Custom Tweaks',
 app_summary='Regolazione delle prestazioni di gioco, impostazioni Play Integrity',
 game_perf_title='Prestazioni di gioco',
 game_perf_on='Attivo',
 game_perf_off='Disattivato',
 game_perf_main_switch='Usa profili di prestazioni per app',
 game_mem_clean_title='Libera memoria per i giochi',
 game_mem_clean_summary="Chiude le app in background quando si apre un'app dell'elenco",
 game_apps_category='App',
 game_app_add='Aggiungi app',
 game_app_remove='Rimuovi',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer="Un profilo si applica solo mentre la sua app è sullo schermo. Le frequenze tornano normali quando esci dall'app. La protezione termica resta sempre attiva.",
 game_custom_cpu_title='Frequenza CPU',
 game_custom_gpu_title='Limite GPU',
 game_custom_range_summary='30–100%',
 game_custom_cpu_summary='Personalizzato %1$d%%',
 game_custom_gpu_summary='Personalizzato %1$d%%',
 game_custom_level='Personalizzato',
 play_store_category='Play Store',
 reboot_title='Riavvio necessario',
 reboot_now='Riavvia',
 reboot_later='Più tardi',
 game_perf_summary="Profili CPU e GPU per app; le impostazioni valgono solo mentre l'app è sullo schermo",

 game_level_entries=['Risparmio energetico', 'Bilanciato', 'Predefinito'],

 game_cpu_level_summaries=['Frequenze più basse per meno calore e più tempo di gioco', "Limita il core principale e gli altri all'80% per sessioni lunghe stabili", 'Frequenze originali; la protezione termica resta attiva', 'Imposta tu i limiti singolo e multi core'],

 game_gpu_level_summaries=['Frequenza grafica più bassa per meno calore', "Frequenza grafica limitata all'80% per sessioni lunghe stabili", 'Frequenza grafica originale', 'Imposta tu il limite di frequenza grafica'],

 installer_spoof_title='Segnala Play Store come installatore',
 installer_spoof_summary='Altre app vedono Play Store come installatore delle app installate fuori da Play, così le app che richiedono un’installazione Play (per esempio Notein) continuano a funzionare. Si applica subito; disattivato per impostazione predefinita',
 integrity_fix_summary='Rinnovo Keybox, TEE Simulator e PIF in un unico interruttore; ha effetto dopo un riavvio',
 integrity_settings_title='Impostazioni di Play Integrity Fix',
 integrity_settings_summary='Stato e rinnovo della Keybox, destinazioni del TEE Simulator, PIF',
 cooldown_category='Controlli automatici',
 check_period_title='Intervallo di controllo',
 unlock_cooldown_title='Attesa dopo lo sblocco',
 keybox_state_installed='Installata',
 keybox_state_none='Non installata',
 keybox_state_unavailable='Servizio non disponibile',
 keybox_state_revoked='Revocata da Google',
 keybox_source_title='Origine',
 keybox_serial_title='Numero di serie',
 keybox_auto_title='Rinnovo automatico',
 keybox_auto_summary='Controlla periodicamente il catalogo Keybox e installa una Keybox nuova; gli aggiornamenti si applicano subito',
 keybox_auto_rotate_title='Sostituisci automaticamente se revocata',
 keybox_auto_rotate_summary='Usa la Keybox di riserva e ne scarica una nuova quando Google revoca quella attiva; se disattivato, solo «Rinnova ora» la sostituisce',
 keybox_renew_title='Rinnova ora',
 keybox_renew_summary='Scarica il catalogo e installa una Keybox non revocata',
 keybox_renewing='Rinnovo…',
 keybox_renew_ok='Keybox installata: %1$s %2$s',
 keybox_renew_failed='Rinnovo della Keybox non riuscito',
 keybox_clear_title='Elimina Keybox',
 keybox_clear_summary='Rimuove dal sistema la Keybox installata',
 keybox_clear_confirm='Eliminare la Keybox installata e tutte quelle di riserva? L’attestazione hardware non viene simulata finché non si installa una nuova Keybox.',
 keybox_cleared='Keybox eliminata',
 keybox_pool_title='Keybox di riserva',
 keybox_pool_summary='%1$d di riserva, %2$d numeri revocati registrati',
 keybox_pool_none='Nessuna',
 teesim_on='Attivo',
 teesim_off='Disattivato',
 teesim_targets_category='App target',
 teesim_targets_all='Tutte le app',
 teesim_targets_all_summary='Simula l’attestazione di tutte le app; disattiva per trattare solo l’elenco sotto',
 teesim_target_add='Aggiungi app',
 teesim_target_remove='Tocca per rimuovere',
 teesim_target_remove_confirm='Rimuovere questa app dall’elenco target?',
 teesim_auto_category='Automatico',
 teesim_auto_title='Aggiungi automaticamente le nuove app',
 teesim_auto_summary='Le app appena installate entrano nell’elenco target, quelle disinstallate ne escono; controllo all’installazione e ogni cinque minuti',
 teesim_add_all='Aggiungi tutte le app installate',
 teesim_add_all_summary='Aggiunge tutte le app di terze parti installate adesso',
 teesim_add_all_done='%1$d app aggiunte',
 pif_state_title='Stato di pif.json',
 pif_state_none='Non impostato',
 pif_state_user='Fornito dall’utente',
 pif_state_fetched='Ottenuto automaticamente',
 pif_patch_title='Patch di sicurezza',
 pif_refresh_title='Ottieni ora',
 pif_refresh_summary='Scarica subito le proprietà di build certificate',
 pif_refreshing='Ottenimento…',
 pif_refresh_ok='pif.json aggiornato',
 pif_refresh_failed='Ottenimento non riuscito',
 pif_clear_title='Elimina pif.json',
 pif_clear_summary='Rimuove i dati pif.json ottenuti',
 pif_clear_confirm='Eliminare pif.json?',
 pif_cleared='pif.json eliminato',
 integrity_reboot_message='Questa modifica si applica dopo il riavvio del tablet. Riavviare ora?',
 integrity_reboot_off_message='La disattivazione ha effetto dopo il riavvio, che rimuove anche i dati associati (Keybox, elenco target, pif.json). Riavviare ora?',
 cooldown_entries=['15 minuti', '30 minuti', '1 ora', '2 ore', '3 ore', '4 ore', '5 ore', '6 ore'],
)
L['pt-rBR'] = dict(
 app_name='Custom Tweaks',
 app_summary='Ajuste de desempenho em jogos, configurações do Play Integrity',
 game_perf_title='Desempenho em jogos',
 game_perf_on='Ativado',
 game_perf_off='Desativado',
 game_perf_main_switch='Usar perfis de desempenho por app',
 game_mem_clean_title='Liberar memória para jogos',
 game_mem_clean_summary='Fecha apps em segundo plano ao abrir um app da lista',
 game_apps_category='Apps',
 game_app_add='Adicionar app',
 game_app_remove='Remover',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='Um perfil só se aplica enquanto o app está na tela. As frequências voltam ao normal quando você sai do app. A proteção térmica continua sempre ativa.',
 game_custom_cpu_title='Frequência da CPU',
 game_custom_gpu_title='Limite da GPU',
 game_custom_range_summary='30–100%',
 game_custom_cpu_summary='Personalizado %1$d%%',
 game_custom_gpu_summary='Personalizado %1$d%%',
 game_custom_level='Personalizado',
 play_store_category='Play Store',
 reboot_title='Reinicialização necessária',
 reboot_now='Reiniciar',
 reboot_later='Mais tarde',
 game_perf_summary='Perfis de CPU e GPU por app; as configurações valem só enquanto o app está na tela',

 game_level_entries=['Economia de energia', 'Equilibrado', 'Padrão'],

 game_cpu_level_summaries=['Frequências menores para menos calor e mais tempo de jogo', 'Limita o núcleo principal e os demais a cerca de 80% para sessões longas estáveis', 'Frequências originais; a proteção térmica continua ativa', 'Defina você mesmo os limites de um e vários núcleos'],

 game_gpu_level_summaries=['Frequência gráfica menor para menos calor', 'Frequência gráfica limitada a cerca de 80% para sessões longas estáveis', 'Frequência gráfica original', 'Defina você mesmo o limite de frequência gráfica'],

 installer_spoof_title='Informar a Play Store como instalador',
 installer_spoof_summary='Outros apps veem a Play Store como instaladora dos apps instalados fora dela, então apps que exigem instalação pela Play (por exemplo Notein) continuam funcionando. Aplica-se na hora; desativado por padrão',
 integrity_fix_summary='Renovação da Keybox, TEE Simulator e PIF em um só interruptor; vale após reiniciar',
 integrity_settings_title='Configurações do Play Integrity Fix',
 integrity_settings_summary='Estado e renovação da Keybox, alvos do TEE Simulator, PIF',
 cooldown_category='Verificações automáticas',
 check_period_title='Intervalo de verificação',
 unlock_cooldown_title='Espera após desbloqueio',
 keybox_state_installed='Instalada',
 keybox_state_none='Não instalada',
 keybox_state_unavailable='Serviço indisponível',
 keybox_state_revoked='Revogada pelo Google',
 keybox_source_title='Origem',
 keybox_serial_title='Número de série',
 keybox_auto_title='Renovação automática',
 keybox_auto_summary='Verifica o catálogo de Keybox periodicamente e instala uma Keybox nova; as atualizações valem na hora',
 keybox_auto_rotate_title='Substituir automaticamente se revogada',
 keybox_auto_rotate_summary='Usa a Keybox reserva e baixa uma nova quando o Google revoga a ativa; desativado, só «Renovar agora» a substitui',
 keybox_renew_title='Renovar agora',
 keybox_renew_summary='Baixa o catálogo e instala uma Keybox não revogada',
 keybox_renewing='Renovando…',
 keybox_renew_ok='Keybox instalada: %1$s %2$s',
 keybox_renew_failed='Falha na renovação da Keybox',
 keybox_clear_title='Excluir Keybox',
 keybox_clear_summary='Remove do sistema a Keybox instalada',
 keybox_clear_confirm='Excluir a Keybox instalada e todas as reservas? A atestação de hardware não é simulada até instalar uma nova Keybox.',
 keybox_cleared='Keybox excluída',
 keybox_pool_title='Keybox reservas',
 keybox_pool_summary='%1$d reservas, %2$d números revogados registrados',
 keybox_pool_none='Nenhuma',
 teesim_on='Ativado',
 teesim_off='Desativado',
 teesim_targets_category='Apps alvo',
 teesim_targets_all='Todos os apps',
 teesim_targets_all_summary='Simula a atestação de todos os apps; desative para tratar só a lista abaixo',
 teesim_target_add='Adicionar app',
 teesim_target_remove='Toque para remover',
 teesim_target_remove_confirm='Remover este app da lista alvo?',
 teesim_auto_category='Automático',
 teesim_auto_title='Adicionar novos apps automaticamente',
 teesim_auto_summary='Apps recém-instalados entram na lista alvo e os desinstalados saem; verificação na instalação e a cada cinco minutos',
 teesim_add_all='Adicionar todos os apps instalados',
 teesim_add_all_summary='Adiciona todos os apps de terceiros instalados agora',
 teesim_add_all_done='%1$d apps adicionados',
 pif_state_title='Estado do pif.json',
 pif_state_none='Não definido',
 pif_state_user='Fornecido pelo usuário',
 pif_state_fetched='Obtido automaticamente',
 pif_patch_title='Patch de segurança',
 pif_refresh_title='Obter agora',
 pif_refresh_summary='Baixa as propriedades de build certificadas na hora',
 pif_refreshing='Obtendo…',
 pif_refresh_ok='pif.json atualizado',
 pif_refresh_failed='Falha ao obter',
 pif_clear_title='Excluir pif.json',
 pif_clear_summary='Remove os dados do pif.json obtidos',
 pif_clear_confirm='Excluir o pif.json?',
 pif_cleared='pif.json excluído',
 integrity_reboot_message='Esta mudança vale depois que o tablet reiniciar. Reiniciar agora?',
 integrity_reboot_off_message='Ao desativar, vale após reiniciar, e os dados associados (Keybox, lista alvo, pif.json) são removidos nesse momento. Reiniciar agora?',
 cooldown_entries=['15 minutos', '30 minutos', '1 hora', '2 horas', '3 horas', '4 horas', '5 horas', '6 horas'],
)
L['ru'] = dict(
 app_name='Custom Tweaks',
 app_summary='Настройка игровой производительности, параметры Play Integrity',
 game_perf_title='Производительность в играх',
 game_perf_on='Вкл.',
 game_perf_off='Выкл.',
 game_perf_main_switch='Профили производительности для приложений',
 game_mem_clean_title='Освобождать память для игр',
 game_mem_clean_summary='Закрывает фоновые приложения при запуске приложения из списка',
 game_apps_category='Приложения',
 game_app_add='Добавить приложение',
 game_app_remove='Удалить',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU',
 game_gpu_category='GPU',
 game_perf_footer='Профиль действует, только пока его приложение на экране. После выхода из приложения частоты возвращаются к норме. Защита от перегрева всегда активна.',
 game_custom_cpu_title='Частота ЦП',
 game_custom_gpu_title='Лимит GPU',
 game_custom_range_summary='30–100 %',
 game_custom_cpu_summary='Свой %1$d%%',
 game_custom_gpu_summary='Свой %1$d%%',
 game_custom_level='Свой',
 play_store_category='Play Маркет',
 reboot_title='Требуется перезапуск',
 reboot_now='Перезапустить',
 reboot_later='Позже',
 game_perf_summary='Профили ЦП и ГП для каждого приложения; настройки действуют, пока приложение на экране',

 game_level_entries=['Энергосбережение', 'Баланс', 'По умолчанию'],

 game_cpu_level_summaries=['Пониженные частоты: меньше нагрев, дольше игра', 'Ограничивает главное и остальные ядра примерно до 80 % для стабильности', 'Заводские частоты; защита от перегрева остаётся активной', 'Задайте лимиты одного и нескольких ядер вручную'],

 game_gpu_level_summaries=['Пониженная частота графики: меньше нагрев', 'Ограниченная частота графики примерно до 80 % для долгой игры', 'Заводская частота графики', 'Задайте лимит частоты графики вручную'],

 installer_spoof_title='Указывать Play Маркет как установщик',
 installer_spoof_summary='Другие приложения видят Play Маркет как установщик приложений, установленных в обход Play, поэтому приложения, требующие установки из Play (например Notein), продолжают работать. Применяется сразу; по умолчанию выключено',
 integrity_fix_summary='Обновление Keybox, TEE Simulator и PIF одним переключателем; вступает в силу после перезапуска',
 integrity_settings_title='Настройки Play Integrity Fix',
 integrity_settings_summary='Состояние и обновление Keybox, цели TEE Simulator, PIF',
 cooldown_category='Автоматические проверки',
 check_period_title='Интервал проверки',
 unlock_cooldown_title='Задержка после разблокировки',
 keybox_state_installed='Установлена',
 keybox_state_none='Не установлена',
 keybox_state_unavailable='Служба недоступна',
 keybox_state_revoked='Отозвана Google',
 keybox_source_title='Источник',
 keybox_serial_title='Серийный номер',
 keybox_auto_title='Автоматическое обновление',
 keybox_auto_summary='Периодически проверяет каталог Keybox и устанавливает новую Keybox; обновления применяются сразу',
 keybox_auto_rotate_title='Автоматически заменять при отзыве',
 keybox_auto_rotate_summary='Подставляет резервную и загружает новую Keybox, когда Google отзывает активную; если выключено, заменяет только «Обновить сейчас»',
 keybox_renew_title='Обновить сейчас',
 keybox_renew_summary='Загружает каталог и устанавливает неотозванную Keybox',
 keybox_renewing='Обновление…',
 keybox_renew_ok='Keybox установлена: %1$s %2$s',
 keybox_renew_failed='Не удалось обновить Keybox',
 keybox_clear_title='Удалить Keybox',
 keybox_clear_summary='Удаляет установленную Keybox из системы',
 keybox_clear_confirm='Удалить установленную Keybox и все резервные? Аппаратная аттестация не подменяется, пока не будет установлена новая Keybox.',
 keybox_cleared='Keybox удалена',
 keybox_pool_title='Резервные Keybox',
 keybox_pool_summary='Резервных: %1$d, отозванных номеров: %2$d',
 keybox_pool_none='Нет',
 teesim_on='Вкл.',
 teesim_off='Выкл.',
 teesim_targets_category='Целевые приложения',
 teesim_targets_all='Все приложения',
 teesim_targets_all_summary='Подменяет аттестацию всех приложений; выключите, чтобы обрабатывать только список ниже',
 teesim_target_add='Добавить приложение',
 teesim_target_remove='Нажмите, чтобы удалить',
 teesim_target_remove_confirm='Удалить это приложение из списка целей?',
 teesim_auto_category='Автоматически',
 teesim_auto_title='Автоматически добавлять новые приложения',
 teesim_auto_summary='Новые приложения попадают в список целей, удалённые убираются; проверка при установке и каждые пять минут',
 teesim_add_all='Добавить все установленные приложения',
 teesim_add_all_summary='Добавляет все установленные сторонние приложения',
 teesim_add_all_done='Добавлено приложений: %1$d',
 pif_state_title='Состояние pif.json',
 pif_state_none='Не задано',
 pif_state_user='Предоставлено пользователем',
 pif_state_fetched='Получено автоматически',
 pif_patch_title='Патч безопасности',
 pif_refresh_title='Получить сейчас',
 pif_refresh_summary='Сразу загружает сертифицированные свойства сборки',
 pif_refreshing='Получение…',
 pif_refresh_ok='pif.json обновлён',
 pif_refresh_failed='Не удалось получить',
 pif_clear_title='Удалить pif.json',
 pif_clear_summary='Удаляет полученные данные pif.json',
 pif_clear_confirm='Удалить pif.json?',
 pif_cleared='pif.json удалён',
 integrity_reboot_message='Изменение вступит в силу после перезапуска планшета. Перезапустить сейчас?',
 integrity_reboot_off_message='При выключении изменение вступит в силу после перезапуска, тогда же удалятся связанные данные (Keybox, список целей, pif.json). Перезапустить сейчас?',
 cooldown_entries=['15 минут', '30 минут', '1 час', '2 часа', '3 часа', '4 часа', '5 часов', '6 часов'],
)


def esc(s):
    s = s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')
    if s.startswith('@') or s.startswith('?'):
        s = '\\' + s
    return s


def attrs(s):
    # a literal % without positional args would be taken as a format string
    literal = re.sub(r'%\\d\\$[sd]', '', s)
    return ' formatted="false"' if '%' in literal else ''


HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<!--
     SPDX-FileCopyrightText: 2026 The LineageOS Project
     SPDX-License-Identifier: Apache-2.0
-->
<!-- Generated by tools/custom_strings.py; edit the table there. -->
<resources>
'''

en = L['en']
for lang, table in L.items():
    # Keys a translation does not carry yet fall back to English; English must
    # be complete.
    missing = [k for k, _ in KEYS if k not in table] + [a for a in ARRAYS if a not in table]
    assert not missing or lang != 'en', (lang, missing)
    out = [HEADER]
    for key, _ in KEYS:
        v = table.get(key, en[key])
        if lang != 'en' and v == en[key] and key not in ('app_name',):
            continue
        out.append(f'    <string name="{key}"{attrs(v)}>{esc(v)}</string>\n')
    for a in ARRAYS:
        items = table.get(a, en[a])
        assert len(items) == len(en[a]), (lang, a)
        out.append(f'    <string-array name="{a}">\n')
        for it in items:
            assert it.count('%') <= 1, it  # arrays are not formatted
            out.append(f'        <item>{esc(it)}</item>\n')
        out.append('    </string-array>\n')
    out.append('</resources>\n')
    d = os.path.join(RES, 'values' if lang == 'en' else 'values-' + lang)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'strings.xml'), 'w') as f:
        f.write(''.join(out))
    print(lang, d)
